### ISSUE TITLE
[BUG] Sometimes in the plugin, lang doesn't work correctly and it defaults to english

### ISSUE THREAD

**Issue by thiagogebrimm** [PotatoCraft-Studio/QuickShop-Reremake#1]
### Description

Some buys/sales made in the plugin do not obey the selected language and sometimes it ends up being the default in English, and I use pt-br

### Steps to reproduce

Buy / sell a item

### Expected Behaviour

Keep everything in pt-br as defined in the config

### Screenshots

![image](https://user-images.githubusercontent.com/75040244/142938155-38fe635a-6cfa-4612-b41b-27bc1ff85b95.png)

### `/qs paste` URL

https://paste.helpch.at/utufayiqip

**Comment by sandtechnology** [comment]
Look like pt_pt is not properly handle by language system, will check that later
