### ISSUE TITLE
[BUG] The same text may appear in multiple chats.

### ISSUE THREAD

**Issue by goddy516** [PotatoCraft-Studio/QuickShop-Reremake#100]
### Description

**When you buy your own shop.**

**When bypassing someone else's shop chat.**

In these cases, the same sentence will be displayed multiple times in the chat field.

### Steps to reproduce

**When you buy your own shop.**
When I purchase my shop, I get the message "Cannot get sales" twice.

**When bypassing someone else's shop chat.**
An OP owner or a player with "quickshop.other.open" privileges opens a chest in someone else's shop.

### Expected Behaviour

Both need to appear in the chat only once.

### Screenshots

![2022-02-10_19 09 36](https://user-images.githubusercontent.com/85031961/153385904-24c12819-5843-4fbb-8e76-87fdcf857bed.png)

![2022-02-10_19 04 52](https://user-images.githubusercontent.com/85031961/153384519-d7f6bba5-d681-4bbd-a33a-d579b9a9028b.png)

### `/qs paste` URL

https://paste.helpch.at/owufokayer

**Comment by SrBedrock** [comment]
I'm also having the same problem.
![image](https://user-images.githubusercontent.com/51332006/153556374-28364bce-6286-40a7-9abc-25d6f0796c5d.png)
