### ISSUE TITLE
[BUG] When Quickshop is installed with the NBT API plugin, the words on Quickshop's store sign will disappear

### ISSUE THREAD

**Issue by CrystalEggs** [PotatoCraft-Studio/QuickShop-Reremake#103]
### Description

When Quickshop is installed with the NBT API plugin, the words on Quickshop's store sign will disappear!!!

### Steps to reproduce

Put the NBT API plugin with QuickShop reremake together.

### Expected Behaviour

Please fix it if you can.Thanks a lot!

### Screenshots

![2022-02-11_21 27 30](https://user-images.githubusercontent.com/53514686/153599660-e30258c9-96a0-4c07-b487-65d0fb3b5a20.png)

### `/qs paste` URL

https://paste.helpch.at/irurobapum

**Comment by sandtechnology** [comment]
It's the NBTAPI side issue, please disable NBTAPI in config.yml to fix it.
