### ISSUE TITLE
[BUG] Discussions pages are disabled

### ISSUE THREAD

**Issue by Andre601** [PotatoCraft-Studio/QuickShop-Reremake#108]
### Description

The Template chooser links to non-existing discussions, which should be fixed

### Steps to reproduce

1. Open a new issue
2. Click any of the links for feature requests or similar.

### Expected Behaviour

They should link to actual discussion categories or at the very least to a different place to suggest stuff.

### Screenshots

N/A

### `/qs paste` URL

N/A

**Comment by sandtechnology** [comment]
Fixed by enabling discussions pages
