### ISSUE TITLE
[Crowdin] What is going on with crowdin?

### ISSUE THREAD

**Issue by Andre601** [PotatoCraft-Studio/QuickShop-Reremake#109]
### Description

This is the second time I get an e-mail telling me that there are **several hundreds of Strings** to translate.

![image](https://user-images.githubusercontent.com/11576465/154107302-06c648f1-d355-444a-bef1-96e79b6d8af5.png)

And when I check the editor am I greeted with this:
![image](https://user-images.githubusercontent.com/11576465/154107399-5aaae700-0be9-4a52-9ab5-b67a93a484e6.png)

What is going on here? Is something on your end broken that we lose translations for stuff we made weeks ago?

I'm starting to get annoyed by this, not only because I lose progress on the translation, but also because I lose the context I spend hours writing on Crowdin.

### Steps to reproduce

Idk... It's an issue on your end and nothing I could "reproduce" myself

### Expected Behaviour

The translations shouldn't be lost at all.

### Screenshots

Shared above.

### `/qs paste` URL

N/A

**Comment by sandtechnology** [comment]
It's not your issue in your end, the problem is the Ghost_chu is using outdated translation when creating the another repo, In this case, you can download the file from reremake one then upload that to Hakri one, or create the issue in Ghost-chu's repo: https://github.com/Ghost-chu/QuickShop-Hikari
![image](https://user-images.githubusercontent.com/20417547/154197048-684ee304-4496-4c88-a12c-3dd746f4e3ff.png)

**Comment by sandtechnology** [comment]
Also a huge thanks for adding context in crowdin! Since json could not add such context and this will help all the translators saving time!

**Comment by Andre601** [comment]
> The original translation and context should not be affected.

They are tho.
Context is gone and my image clearly shows that strings got untranslated

**Comment by Ghost-chu** [comment]
> > The original translation and context should not be affected.
> 
> They are tho. Context is gone and my image clearly shows that strings got untranslated

<img width="776" alt="image" src="https://user-images.githubusercontent.com/30802565/154296232-1bac4018-72d9-47cd-a9b5-bf35b91d31c3.png">

Do you remember which string that image was uploaded to?

**Comment by Ghost-chu** [comment]
<img width="451" alt="image" src="https://user-images.githubusercontent.com/30802565/154296615-a6c98b49-460f-46d1-8d43-35058b3561d9.png">

**Comment by Ghost-chu** [comment]
<img width="448" alt="image" src="https://user-images.githubusercontent.com/30802565/154297056-5e282d06-06bd-4310-b48a-92f7c3be854d.png">
Crowdin's translator UI doesn't seem to reflect the multi-file situation very well, but from our backend UI, everything seems to be working fine.
