### ISSUE TITLE
[Minor BUG/TYPO] when someone buys items the chat message's color gets same as item's name color

### ISSUE THREAD

**Issue by SideLo98** [PotatoCraft-Studio/QuickShop-Reremake#112]
### Description

a very minor chat bug when someone buys item from your shop, like whatever the color code is for [item] is added after the rest of the chat message. And there is no space between "purchased[amount]".

### Steps to reproduce

sell any item with colored/formated named, and let someone buy it.

### Expected Behaviour

would be cool if maybe add &r after the purchased [item].
like this: `&a[player] purchased<space here>[amount] [item] &r&afrom your shop and you earned [money]..the rest message`

### Screenshots

![image](https://user-images.githubusercontent.com/67060780/154914914-f0933e7b-349c-4e83-86b5-e1e5fd072cc9.png)

### `/qs paste` URL

https://paste.helpch.at/birulivada

### Additional Context

thanks, and sorry if I posted in wrong topic.

**Comment by sandtechnology** [comment]
You can use [override system](https://github.com//PotatoCraft-Studio//QuickShop-Reremake//wiki//Use-translation-override-system) to fix that, just replace the file in `override/en_us/messages.json` with following content:
```
{
  "player-bought-from-your-store-tax": "&c{0} purchased {1} {2} &r&afrom your shop, and you earned {3} ({4} in taxes).",
  "player-bought-from-your-store": "&c{0} purchased {1} {2} &r&afrom your shop, and you earned {3}."
}
```

**Comment by SideLo98** [comment]
Thank you, I've changed it. But still I will suggest the default message to include it. you may close this issue thanks again.
