### ISSUE TITLE
[BUG] Players can only sell their items to double chests in small increments, despite the shop being Unlimited

### ISSUE THREAD

**Issue by bachikin** [PotatoCraft-Studio/QuickShop-Reremake#152]
### Description

Both me and another player on our server have an issue where despite having, say, 64 iron ingots, when selling to an Unlimited shop it only allows us to sell less than that amount.

I've been told that someone was only able to sell 4 iron at a time despite having much more in their inventory, and thus they have to keep clicking the sign over and over to sell all their iron.

This isn't just with iron ingots, this issue has also happened to me with stone and cobblestone. In the screenshots attached, I have 64 cobblestone in my hand, yet am only able to sell 2.

Extra info: As for as I'm aware, this issue has only happened with double chest shops. I've just tested it on an Unlimited single chest, and it seems to be working fine.

### Steps to reproduce

1. Place two small chests next to each other to create a large chest.
2. Use the /qs create command to create a shop. (I usually use the format /qs create 2 cobblestone).
3. Make the shop Unlimited by using the /qs unlimited and /qs alwayscounting commands, as well as make one of the signs able to buy with /qs buy.
4. Have the items you'd like to sell in your inventory.
5. Left click the Buy sign, and type "all" in chat when prompted to.

### Expected Behaviour

When typing "all" in chat when prompted, I should be able to sell all of that item available in my inventory, rather than just a few at a time.

### Screenshots

![image](https://user-images.githubusercontent.com/102389252/161344811-a04381b3-f7f1-4409-b178-9dcfd127b2f0.png)
![image](https://user-images.githubusercontent.com/102389252/161344885-09519438-1caa-4a16-9d6d-ee3e69a3fab9.png)

### `/qs paste` URL

https://paste.helpch.at/bovowunari

### Additional Context

Server is 1.17.1 Spigot, using the latest version of Quickshop (I updated in-game when the latest update came out, and restarted the server afterwards.)

**Comment by sandtechnology** [comment]
Could not reproduce this in 1.17.1, considering server software issue, please try to update your spigot:
![20220404113052](https://user-images.githubusercontent.com/20417547/161469320-f2a41c2f-c517-4050-bb3c-803840fb29ac.jpg)
