### ISSUE TITLE
[BUG] Players will get double the amount for buying their own item account

### ISSUE THREAD

**Issue by kevinwang-0916** [PotatoCraft-Studio/QuickShop-Reremake#155]
### Description

Players will get double the amount for buying their own item account

### Steps to reproduce

Players will get double the amount for buying their own item account

### Expected Behaviour

Balance unchanged

### Screenshots

![1](https://user-images.githubusercontent.com/69382843/162198751-8bca3a91-326d-4351-919d-9bd7c730b76a.png)
![2](https://user-images.githubusercontent.com/69382843/162198763-3b1114b3-0751-4932-bcb1-ce847063472a.png)
![3](https://user-images.githubusercontent.com/69382843/162198771-25d3f774-b413-4ba4-9af2-a0aa7bfc4836.png)
![4](https://user-images.githubusercontent.com/69382843/162198780-c68c5f1a-5d30-402f-b828-58515553100a.png)

### `/qs paste` URL

https://paste.helpch.at/ofukosunif

**Comment by sandtechnology** [comment]
Please check if there have any configuration error with XConomy and MysqlPlayerDataBridge, it shouldn't is the quickshop issue
