### ISSUE TITLE
Help changing the currency

### ISSUE THREAD

**Issue by TheGame22** [PotatoCraft-Studio/QuickShop-Reremake#159]
I wanted to change the currency, but the config file says to ask for support if you don’t know what you are doing, and that is me. If anyone could help me, that would be great.

**Comment by sandtechnology** [comment]
You need to install the plugin supports muti-currency listed in eco-type then set `eco-type` to corresponding type, after then, create a currency in eco plugin then use that in quickshop like `/qs currency <currency name>`:
> /qs currency <currency name>
> Command to specified the currency the shop using.
> The Economy plugin must support the Multi Currency feature and supported by QuickShop. We support GemsEconomy and > TNE now.
