### ISSUE TITLE
[BUG] Unlimited shop does not work

### ISSUE THREAD

**Issue by Nemozxy** [PotatoCraft-Studio/QuickShop-Reremake#163]
### Description

When unlimited shop is full(whether that shop is sold or bought),it does not work.It will show
![image](https://user-images.githubusercontent.com/103293222/165567960-aa1b6ab2-9af1-45e0-b8b5-8edabe809744.png)
to cue the player that the store is full and needs to be emptied.
game version:paper-1.18.2-284
plugin version:5.1.0.6
(My English is not very good, there may be some unclear expression, sorry)

### Steps to reproduce

1.creat shop
2.set the shop unlimited
3.fill the shop
4.try to buy or sell
5.shop does not work

### Expected Behaviour

Please fix this bug.Thank you.

### Screenshots

I'm so sorry it's chinese.
![2](https://user-images.githubusercontent.com/103293222/165579885-fb99f678-4f0d-4986-9afb-b3f89319f644.gif)
![1](https://user-images.githubusercontent.com/103293222/165579898-128c5b68-3df0-4870-a5c3-1b73a30944c2.gif)

### `/qs paste` URL

https://paste.helpch.at/oliwikerev

### Additional Context

My English is not very good, there may be some unclear expression.

**Comment by sandtechnology** [comment]
It should be not a bug but works as intended, please disable alwayscounting for shop to fix it (facing to shop then type /qs alwayscounting)
