### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by JustinBery** [PotatoCraft-Studio/QuickShop-Reremake#164]
### Description

quickshop.tax permission is invalid

### Steps to reproduce

Test still deducted tax after adding permissions

### Expected Behaviour

Normally, permission should be given, no tax deduction

### Screenshots

No error reported

### `/qs paste` URL

No error reported

**Comment by sandtechnology** [comment]
Please check you permission plugin by /vault-info, also paste is needed for this issue

**Comment by JustinBery** [comment]
> 请通过 /vault-info 检查您的权限插件，此问题也需要粘贴

[00:47:39 INFO]: [Vault] Vault v1.7.3-CMI Information
[00:47:39 INFO]: [Vault] Economy: CMIEconomy [CMIEconomy]
[00:47:39 INFO]: [Vault] Permission: LuckPerms [LuckPerms, SuperPerms]
[00:47:39 INFO]: [Vault] Chat: LuckPerms [LuckPerms]

**Comment by sandtechnology** [comment]
> > 请通过 /vault-info 检查您的权限插件，此问题也需要粘贴
> 
> [00:47:39 INFO]: [Vault] Vault v1.7.3-CMI Information [00:47:39 INFO]: [Vault] Economy: CMIEconomy [CMIEconomy] [00:47:39 INFO]: [Vault] Permission: LuckPerms [LuckPerms, SuperPerms] [00:47:39 INFO]: [Vault] Chat: LuckPerms [LuckPerms]

Are you using machine translator? 请提供/qs paste的链接

**Comment by JustinBery** [comment]
https://paste.helpch.at/osusaxadal.使用测试服的数据。插件与正式服一致

**Comment by sandtechnology** [comment]
> https://paste.helpch.at/osusaxadal. 使用测试服的数据。插件与正式服一致 正式服核心是pur最新版。测试服测试使用paper也一样有这个问题

请测试一次后再/qs paste 需要得知当时的权限情况 怀疑是LP自身问题导致

**Comment by Ghost-chu** [comment]
Tax 的权限计算依赖于主动交易的一方。

QuickShop 无法检查离线玩家的权限，因此，如果你是店主，只有当 购买/出售 者拥有 Tax 减免权限时才会生效。
