### ISSUE TITLE
[BUG] SuperiorSkyblock2 hook on coop.

### ISSUE THREAD

**Issue by LuluxClient** [PotatoCraft-Studio/QuickShop-Reremake#167]
### Description

When adding a coop member to your island they are able to create quickshop shops but the issue with it is that some people do not wish to have coop have access to chests so they juste create them and they cannot refill the shop et the island members and owners cannot remove the quickshop. In the end some island have quickshops that are stucked for a lifetime.

### Steps to reproduce

1. Create an island
2. add a player as a coop /is coop <player>
3. Ask the coop member to create a quickshop
4. kick the coop or just disconnect (upon disconnecting all the coops are automatically kicked)
5. boom

### Expected Behaviour

Quickshop should either prevent the creation of the quickshop if you cannot access to containers and after leaving they should lose their quickshop (each of these should be a config option)

### Screenshots

none

### `/qs paste` URL

0 errors

### Additional Context

none

**Comment by sandtechnology** [comment]
How about this version?
https://ci.codemc.io/job/PotatoCraft-Studio/job/QuickShop-Reremake-SNAPSHOT/2322/artifact/target/QuickShop-5.1.0.7-SNAPSHOT.jar
