### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by dryter97** [PotatoCraft-Studio/QuickShop-Reremake#17]
### Description

hello there so... i got this weird thing in chat when user want to buy on a shot

any solution? 
running 5.0.0.17 from 3 december
occure also on 5.0.0.16 reason why we jumped on dev build.

this message im talking about is the line 112 in message.json
at the buttom you can see "enter in chat, how many you wish to BUY. you can buy 0 Enter all to buy them all.

wich is 0 the issus i actually got 4 empty slot and 4*64 = 256 i can buy 
its not doing it only for the iron and its also doing it for player limited amount shop too.

### Steps to reproduce

create a chest.

put some item in it to sell it from quickshop.

tap on it to by some

read the chat

### Expected Behaviour

not showing 0 but the amounth you are suposed to be able to buy

### Screenshots

![image](https://cdn.discordapp.com/attachments/471882812270706719/917257921484701736/unknown.png)

### `/qs paste` URL

https://paste.helpch.at/vubakukotu

**Comment by sandtechnology** [comment]
How about using latest snapshot？https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/

**Comment by dryter97** [comment]
we compiled it yesterday the 5 december still the 5.0.0.17 your request is erelevant no chan ge has been done since the 3 december.

**Comment by sandtechnology** [comment]
How about setting work-type to 1 in config.yml?

**Comment by sandtechnology** [comment]
How about this version? https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/2035/

**Comment by dryter97** [comment]
Both is not result

**Comment by dryter97** [comment]
@sandtechnology  founded out its doing it for some precise item. its realy weird. minecraft got too much different item to test it out alone but there is one exemple

![image](https://cdn.discordapp.com/attachments/528666966886711306/918182513741021184/unknown.png)

**Comment by sandtechnology** [comment]
https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/2039/ How about this version?

**Comment by dryter97** [comment]
i just tested it out. into a test server. im gonna test it with a server  owner who complain about it to me. so we will get more direct result and better answer. ill let you know if that persist.

**Comment by sandtechnology** [comment]
> i just tested it out. into a test server. im gonna test it with a server owner who complain about it to me. so we will get more direct result and better answer. ill let you know if that persist.

https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake/124/artifact/target/QuickShop-5.1.0.1.jar
It was the latest stable version including this fix, feel free to reporting bugs!

**Comment by dryter97** [comment]
this bug still persist. are you even testing it yourself?
i mean closing an issue so fast without waiting for a reply is kinda showing the user you dont care of this bug.
to be honest this still persist even with all the trick you gived above even if you change it direcly on the github its not gonna change it on user server....

so yea are you planning for a real patch or just a "you are dumb" answer like those 3 last one?

dont take minecraft server owner and user has newbee user.... we can be range from 13 years of server usage to same day newbee. 

Saddly we are not all robot like i said on your discord. We can spend time working the week and find out this ticket is close 3 day after you commented.

i personally took time before answering cause man im pissed.

im pissed to see this plugins going into your hand and going so fast people dont even got time to try it all correcly.

did you ever tought some person can be managing a server and seeking help with community and this person will go here to report a bug the server owner in first place will not want to report himself? 

anyway. i wich this text is clear enough to make you think a bit about how you should manage issue ticket on github.
