### ISSUE TITLE
[PERFORMANCE] QuickShop performance problem.

### ISSUE THREAD

**Issue by matipoirierg** [PotatoCraft-Studio/QuickShop-Reremake#177]
### Description

30 - 50 online players servers with default quickshop settings.

### Steps to reproduce

General bad performance.

### Expected Behaviour

being less resource intensive.

### Screenshots

![qs](https://user-images.githubusercontent.com/97362850/170603681-f86fb13d-4180-455e-9a0c-afd4c0ef8565.JPG)
![qs2](https://user-images.githubusercontent.com/97362850/170603690-dfef5234-df5b-4c4f-9a55-79ce487919b2.JPG)

### `/qs paste` URL

https://paste.helpch.at/unusukotog

### Spark Sample URL

https://spark.lucko.me/EKkVWwWvuA

**Comment by sandtechnology** [comment]
Closed due to it has been fixed in the latest version of quickshop (5.1.0.7)
