### ISSUE TITLE
Sumoon wither and get the things

### ISSUE THREAD

**Issue by NotKillerGod** [PotatoCraft-Studio/QuickShop-Reremake#206]
### Description

When players summon wither, the store created by quickshop will be destroyed and things will be taken by players
Quickshop version:4.0.9.10
The config  protect is on

### Steps to reproduce

1.Create a chestshop
2.Sumoon a wither
3.And you can pass the lock to get the thing
 

### Expected Behaviour

Update the plugin and fix this bug

### Screenshots

![QQ截图20220708132043](https://user-images.githubusercontent.com/89688029/177922688-93b4a64a-cd5e-4707-af3e-92d52d546c53.png)

### `/qs paste` URL

https://paste.ubuntu.com/p/YdWfT9ZN6R/

**Comment by NotKillerGod** [comment]
> ### Description
> When players summon wither, the store created by quickshop will be destroyed and things will be taken by players Quickshop version:4.0.9.10 The config protect is on
> 
> ### Steps to reproduce
> 1.Create a chestshop 2.Sumoon a wither 3.And you can pass the lock to get the thing
> 
> ### Expected Behaviour
> Update the plugin and fix this bug
> 
> ### Screenshots
>
![QQ截图20220708132043](https://user-images.githubusercontent.com/89688029/177922638-e743e3d6-5660-42e3-834f-6e7dd2e17a1a.png)

> 
> ### `/qs paste` URL
> https://paste.ubuntu.com/p/YdWfT9ZN6R/
> 
> ### Additional Context
> _No response_

**Comment by sandtechnology** [comment]
It seems you are using outdated configuration, anyway, you can manually add and enable `enchance-shop-protect` at config.yml which after shop node like this:
```
shop:
  cost: 0
  enchance-shop-protect: true
```
