### ISSUE TITLE
[BUG] Fake BlockBreakEvent when shop cant be created

### ISSUE THREAD

**Issue by Acablade** [PotatoCraft-Studio/QuickShop-Reremake#218]
### Description

It fires a blockbreakevent whenever you dont input a number as price

### Steps to reproduce

1. Put a chest
2. Left Click
3. Type anything but number in chat
4. BlockBreakEvent gets fired

### Expected Behaviour

1. Put a chest
2. Left Click
3. Type anything but number in chat
4. BlockBreakEvent **DOES NOT** get fired

### Screenshots

https://prnt.sc/BdyKOg94aQxi
i have a custom plugin which sends the fired message on blockbreakevent

### `/qs paste` URL

https://paste.helpch.at/zaponefapa

**Comment by sandtechnology** [comment]
https://www.spigotmc.org/resources/quickshop-reremake-1-19-ready-multi-currency.62575/
Known Incompatible Plugins
Some plugins may not work together with QuickShop and there is little we can do on our side to fix this.

    Pretty much any BungeeCord Chat plugin.
    Those override the default per-server chat and it's impossible to fix this without any bungee-spigot bridge-plugins.
    You can use /qs amount <amount> to set the price instead.
    Plugins handling BlockBreakEvents
    You can disable protection-checking and use the integration-option to check if you can create a shop.
    Note that this allows players to create shops everywhere!
    ChatControl Pro/Red
    You can use /qs amount <amount> to set the price instead.
