### ISSUE TITLE
[BUG] Toggledisplay broken on latest version and 1.19

### ISSUE THREAD

**Issue by pacificminer** [PotatoCraft-Studio/QuickShop-Reremake#224]
### Description

After updating my server to 1.19 and QuickShop to the latest version: 5.1.0.9, the /qs toggledisplay now no longer works as intended. If players wish to hide the item hologram, and type /qs toggledisplay, it is disabled for about a second before the item hologram returns. This effectively makes it impossible to hide the shop's item hologram.

### Steps to reproduce

Create a Shop and do /qs toggledisplay

### Expected Behaviour

The item shouldn't display when toggled

### Screenshots

N/A

### `/qs paste` URL

*

**Comment by sandtechnology** [comment]
What about your `/qs paste` URL? Without this we can't do anything

**Comment by sandtechnology** [comment]
Anyway, just check the code and found this may cause this, but still, without `/qs paste` URL, we could not know what environment you are, you can test it with this build: https://ci.codemc.io/job/PotatoCraft-Studio/job/QuickShop-Reremake-SNAPSHOT/2393/artifact/target/QuickShop-5.1.0.10-SNAPSHOT.jar

**Comment by pacificminer** [comment]
> Anyway, just check the code and found this may cause this, but still, without `/qs paste` URL, we could not know what environment you are, you can test it with this build: https://ci.codemc.io/job/PotatoCraft-Studio/job/QuickShop-Reremake-SNAPSHOT/2393/artifact/target/QuickShop-5.1.0.10-SNAPSHOT.jar

Works again. Thank you
