### ISSUE TITLE
Broken shops for certain items [BUG] 

### ISSUE THREAD

**Issue by Danifoxe** [PotatoCraft-Studio/QuickShop-Reremake#23]
### Description

There are shops that are unusable for certain objects, usually they are emerald diamond type objects, etc. When you try to buy an object, only the name of the store owner appears and no other options. Likewise, when you try to create a store with this type of object, there is no interaction of any kind and the store cannot be created. 

### Steps to reproduce

1. Click on shop.
2. It only appears the name of the owner and no other options.

1. Place a chest on the ground.
2. Have an object, for example an emerald or diamond.
3. Left click on the chest.
4. Nothing happens. 

### Expected Behaviour

- Buy normally in a shop.

- Normally create a shop. 

### Screenshots

- When creating a shop.
![imagen](https://user-images.githubusercontent.com/59784220/145412959-96fb2851-fcdc-4e80-a061-fc4d3889f124.png)

- When trying to buy in a shop.
![imagen](https://user-images.githubusercontent.com/59784220/145412856-c95a2d43-3e7b-4795-a3ad-a51ef3a4d447.png)

### `/qs paste` URL

https://paste.helpch.at/wehodehixa

### Additional Context

This server is running Paper version git-Paper-63 (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT) (Git: bbc7451)
You are running the latest version
Previous version: git-Paper-61 (MC: 1.18)

Console log:
https://paste.helpch.at/jogegubafo.sql

**Comment by Danifoxe** [comment]
Solved with QuickShop-5.0.0.17-SNAPSHOT.jar build #2038 . Sorry for opening the report. Please close it.

**Comment by sandtechnology** [comment]
Author itself could close this issue, I just forgot to reply as it was duplicated with #16 and has been solved, feel free to reopen it if still have this issue
