### ISSUE TITLE
[BUG] Towny Integration not working correctly

### ISSUE THREAD

**Issue by SideLo98** [PotatoCraft-Studio/QuickShop-Reremake#239]
### Description

won't let create shop both inside and outside of town using towny integration enable: true with

```
create:
- MODIFY
```
and
```
whitelist-mode: true
```

### Steps to reproduce

enable towny integration in config
place 1 chest inside town
place 2nd chest outside town
type /qs create 1 in both
it will give error: Integration Towny denied the shop-creation.

### Expected Behaviour

it should prevent shop-creation outside towns but not inside town when whitelist-mode is true

### Screenshots

![2022-09-20_09 21 13](https://user-images.githubusercontent.com/67060780/191168038-5d28e0b7-39d7-4686-8ca5-4a45f39609e4.png)
![2022-09-20_09 20 58](https://user-images.githubusercontent.com/67060780/191168042-020d19cf-0a34-4f61-9a80-a9f709f4bf92.png)

### `/qs paste` URL

https://paste.helpch.at/qihaxiyovi

**Comment by sandtechnology** [comment]
Due to the Towny api limitation, integration needs shop was built at shop plot
