### ISSUE TITLE
plugins 

### ISSUE THREAD

**Issue by saraBota** [PotatoCraft-Studio/QuickShop-Reremake#244]
### Description

im install plugin in file’s and he is not working 

### Steps to reproduce

![085D768E-3FE5-406B-9BB8-757324F43FBF](https://user-images.githubusercontent.com/111562273/193620083-ba5a2571-6cae-475e-836a-5cf4a436580c.jpeg)
![5EF80237-54D4-4ECA-8361-0D8697FC4D37](https://user-images.githubusercontent.com/111562273/193620096-6b7b1e2f-7540-4a70-a37d-07e434016a17.jpeg)

### Expected Behaviour

im install plugin in files and not working 

### Screenshots

![3C0AE569-02C6-415B-A47C-8D3354B4512B](https://user-images.githubusercontent.com/111562273/193619130-9e09c1e5-8d0a-4660-a751-331121c560cb.jpeg)
![Uploading 00AF12EF-3078-4D49-97F7-90AA17F4CFDA.jpeg…]()

### `/qs paste` URL

https://paste.helpch.at/iduzucoqak.makefile

**Comment by saraBota** [comment]
hmm

**Comment by saraBota** [comment]
> 

ok thx

**Comment by saraBota** [comment]
> > Caused by: java.lang.SecurityException: SHA-256 digest error for org/maxgamer/quickshop/QuickShop.class
> 
> QuickShop jars contain build data that allow you to check if a jar has been modified. Newer builds have a built-in self-checker that sends you warnings. The warning usually looks like SHA-1/256 digest error or Security risk detected and most of them point to org/maxgamer/quickshop/QuickShop.class. Once you see one of them, your Server has been infected! This is usually caused by the "L10" malware
> 
> If that is the case, then:
> 
> 1. Delete the malicious Plugin immediately!
> 2. Make a full backup of your Server
> 3. Scan your Server with this Anti-Malware Tool: https://www.spigotmc.org/resources/spigot-anti-malware-detects-over-300-malicious-plugins.64982/
> 4. Delete the malicious jar it reported
> 5. Re-download deleted jar, then scan again to make sure you got rid of the malware (May have false-positive, so feel free to ask if not sure)
> 6. You're done.

not work

**Comment by sandtechnology** [comment]
You need to replace ALL of jars in plugins folder by **once**, and download those jar from official site
