### ISSUE TITLE
[BUG] Shulker shops drop the sign and disappear when you use a piston!

### ISSUE THREAD

**Issue by smuddgge** [PotatoCraft-Studio/QuickShop-Reremake#248]
### Description

When you create a QS shop with a shulker and then you use a piston to break the shulker. It drops the sign and breaks the shop.

### Steps to reproduce

- Create a QS shop on a shulker
- Break it with a piston

### Expected Behaviour

You are ether unable to break the shop or it does not drop a sign!

### Screenshots

![2022-10-29_22 13 30 copy](https://user-images.githubusercontent.com/68658429/198852553-70acc06a-2071-482e-88db-e74ff35e7359.png)
![2022-10-29_22 13 35 copy](https://user-images.githubusercontent.com/68658429/198852559-1b8bbef7-008f-4fbf-9314-7defedadc134.png)
![2022-10-29_22 13 42 copy](https://user-images.githubusercontent.com/68658429/198852561-1020fc51-cbc8-42bb-b96b-1f76abd216bb.png)

### `/qs paste` URL

https://paste.helpch.at/iyowoyotas

**Comment by sandtechnology** [comment]
Shulker will be added to shop-black-list in the next version, you can just remove it to fix it
(For why I don't fix it is because there are so many container thing you can use, and it's user choice)

**Comment by sandtechnology** [comment]
Edit: look like we have `enchance-shop-protect` setting, which will prevent such bug, could you enable it and test again?

**Comment by smuddgge** [comment]
Hey there, I have just tested both protection config options and they do not fix the bug.
```yaml
#Use enhanced display protection.
enchance-display-protect: true

#Use enhanced shop protection.
enchance-shop-protect: true
```

I understand shulkers can be disabled but it would be nice to be fixed as it's a shop option and stop players from duplicating signs.

**Comment by smuddgge** [comment]
With that build, for some reason, i am now unable to even create a shop o:

```yml
shop-blocks:
- CHEST
- TRAPPED_CHEST
- ENDER_CHEST
- SHULKER_BOX
```

<img width="913" alt="Screenshot 2022-11-03 at 21 25 04" src="https://user-images.githubusercontent.com/68658429/199837226-0aed6fc8-dad1-4a8f-9f75-bd27ebed1574.png">

**Comment by sandtechnology** [comment]
> ```yaml
> SHULKER
> ```

This build should fix it: https://ci.codemc.io/job/PotatoCraft-Studio/job/QuickShop-Reremake-SNAPSHOT/2402/artifact/target/QuickShop-5.1.0.10-SNAPSHOT.jar

**Comment by smuddgge** [comment]
All fixed now, thank you ❤️
