### ISSUE TITLE
[BUG] Plugin Does not work

### ISSUE THREAD

**Issue by ghost** [PotatoCraft-Studio/QuickShop-Reremake#249]
### Description

When you left click chest and enter an amount in chat it says nothing
When you left click chest and use `/qs amount 10000` it still just says "An Internal error occurred" but no shop is created
![Uploading image.png…]()

### Steps to reproduce

1- Right click a chest
2 - Enter amount in chat

or

1- Right click a chest
2- Use `/qs amount 10000`

### Expected Behaviour

Shop should be created

### Screenshots

![image](https://user-images.githubusercontent.com/97077949/199229844-183f311e-d8bc-4bfb-975e-7f9fa2d2745f.png)
![image](https://user-images.githubusercontent.com/97077949/199229903-61a20f1d-2271-4195-bc3f-82c4bbcceadb.png)
![image](https://user-images.githubusercontent.com/97077949/199229984-b5b769fe-7707-4650-a8ef-3faf9de950af.png)
![image](https://user-images.githubusercontent.com/97077949/199230006-50857121-e994-47cf-85fc-6bfb1d531a27.png)

### `/qs paste` URL

https://paste.helpch.at/yadozetiqu

### Additional Context

N/A

**Comment by sandtechnology** [comment]
Please post the error in console

**Comment by sandtechnology** [comment]
> ![image](https://user-images.githubusercontent.com/97077949/199582534-46905cfb-8cfb-4296-9859-129246a91669.png) [previous one] ![image](https://user-images.githubusercontent.com/97077949/199582091-5babff9d-6f82-4a37-9431-d8d01775ca00.png)

Could you post the FULL server log in there (You can hide sensitive information in your log)?
And you can try to disable integration and see if it still happening
