### ISSUE TITLE
[BUG] /shop command bugging with Economyshopgui plugin

### ISSUE THREAD

**Issue by Patykqs** [PotatoCraft-Studio/QuickShop-Reremake#259]
### Description

Can't use /shop command for economyshopgui because the quickshop one overrides it. Is there a way to disable the /shop command in quickshop (so that the other ones like /qs stay?) i would love to know if that is possible because i cant open the economyshopgui with the /shop command and have to use economyshopgui:shop. 

I deleted custom commands or whatever it was called.

### Steps to reproduce

1.Add an option to disable some commands in the config.yml file.

### Expected Behaviour

quickshop should be able to disable the /shop command because there are more like /qs

### Screenshots

![image](https://user-images.githubusercontent.com/118213457/202778871-d1663d87-807f-4860-85f0-e74e090f6b92.png)
instead of
![image](https://user-images.githubusercontent.com/118213457/202778920-533171fa-c172-44f1-82d5-c414b6b732d7.png)

### `/qs paste` URL

https://paste.helpch.at/vukeriguku

**Comment by sandtechnology** [comment]
In `config.yml`, search `- shop` then remove it

**Comment by sandtechnology** [comment]
Wait...look like your config.yml is missing this option, you can setting `config-damaged` to `true` then let quickshop fix it
