### ISSUE TITLE
[PERFORMANCE] Checking Database Column Takes A While

### ISSUE THREAD

**Issue by Kyrobi** [PotatoCraft-Studio/QuickShop-Reremake#260]
### Description

When the server is starting up, it hangs waiting for QuickShop to check and update the database columns. I have about ~1400 shops on the server, so I do not know why it is taking so long.

https://hastebin.com/awinanolob.yaml

You can see from the timestamp that it took the plugin several hours to check and update the columns.

This is the second time this has happened.

We recently switched from SQLite to using MySQL. I migrated all the data over to SQL.
2 days later, when the server got stuck trying to load, I thought there was a problem with the database. I delete the SQL database and reimported the save.

And then earlier this morning when the server was restarting, it happened again. The server got stuck trying to start. I was asleep during this time, so by the time I woke up, the server has started. Players pinged me on how the server was down for a while.

### Steps to reproduce

I am not sure, however, I guess it is because my migrating from SQLite to MySQL probably.

1. Run /qs export
2. Switch to MySQL connection
3. Run /qs convert MySQL

### Expected Behaviour

The plugin should not try to update the columns for several hours.

### Screenshots

N/A

### `/qs paste` URL

https://paste.helpch.at/hehuyizafa

### Spark Sample URL

Irrelevant 

### Additional Context

N/A

**Comment by sandtechnology** [comment]
You can use sqlite database for workaround, our plugin is not recommended to use sqlite, and this issue should take some time to solve since mysql should not have a convenient command to check that.

**Comment by Kyrobi** [comment]
It seems like this no longer happens after the initial column update. I will reopen this issue if it occurs again.
