### ISSUE TITLE
[BUG] Dont work in 1.19.3

### ISSUE THREAD

**Issue by moda84** [PotatoCraft-Studio/QuickShop-Reremake#267]
### Description

![image](https://user-images.githubusercontent.com/44532692/206902986-2cf8a4a3-5cfa-4545-b193-e67463fb9581.png)
(Without plugin - no error)

PLUGIN VERSION: 
Test 1: QuickShop-5.1.0.9
Test 2: QuickShop-5.1.0.10-SNAPSHOT.jar (last for 11 dec 2022)

CORE VERSION:
Purpur, 1.19.3

### Steps to reproduce

1. Player spawn near QuickShop chest
2. Player was kicked
3. Console send error
Without plugin - no kick and no console error

PLUGIN VERSION: 
Test 1: QuickShop-5.1.0.9
Test 2: QuickShop-5.1.0.10-SNAPSHOT.jar (last for 11 dec 2022)

CORE VERSION:
Purpur, 1.19.3

### Expected Behaviour

Stable work

### Screenshots

![image](https://user-images.githubusercontent.com/44532692/206903024-4eed85e8-936b-4725-8bba-649c90e1decc.png)

### `/qs paste` URL

https://paste.helpch.at/obegokevox.makefile

**Comment by sandtechnology** [comment]
See https://github.com/dmulloy2/ProtocolLib/pull/1946#issuecomment-1344931249, Quickshop needs the new type constructor from ProtocolLib for supporting 1.19.3

**Comment by sandtechnology** [comment]
You can set `display-type` to `0` to use RealDisplayItem for workaround

**Comment by sandtechnology** [comment]
https://ci.codemc.io/job/PotatoCraft-Studio/job/QuickShop-Reremake-SNAPSHOT/2414/
This version should work for VirtualDisplayItem and it needs [dev build](https://ci.dmulloy2.net/job/ProtocolLib/) for protocollib: https://ci.codemc.io/job/PotatoCraft-Studio/job/QuickShop-Reremake-SNAPSHOT/2414/artifact/target/QuickShop-5.1.0.10-SNAPSHOT.jar
