### ISSUE TITLE
[BUG] Chestshop sign not displaying text

### ISSUE THREAD

**Issue by haxbob12345** [PotatoCraft-Studio/QuickShop-Reremake#278]
### Description

When I used the quickshop plugin and the plugin created the sign for the shop, it does not display the text of the shop information on the sign like it normally would.
![image_2022-12-21_114429781](https://user-images.githubusercontent.com/40577851/208945058-2424e7ab-2b5c-4ac3-a224-8c38b4062838.png)

### Steps to reproduce

I'm not sure how to reproduce the bug but I did the following during the install,

1. Download the latest plugin version from spigot
2. Download protocollib (for versions 1.18 and lower)
3. Dragged into plugins folder of server
4. Started the server
5. Attempt to make a shop 
6. No sign showing

### Expected Behaviour

I expected the plugin to create the shop as normal (with the sign text) but it doesn't display the text on the sign. 

### Screenshots

![image_2022-12-21_114636909](https://user-images.githubusercontent.com/40577851/208945516-8c27b64d-756e-4667-8567-ba97b2688d5c.png)

### `/qs paste` URL

https://paste.helpch.at/saloyidemi

**Comment by sandtechnology** [comment]
try to install this plugin?https://github.com/UltraVanilla/cleanupstupidmojangshit/releases/tag/v1.1.0

**Comment by haxbob12345** [comment]
What does this do?

**Comment by haxbob12345** [comment]
> try to install this plugin?https://github.com/UltraVanilla/cleanupstupidmojangshit/releases/tag/v1.1.0

What does it do?

**Comment by sandtechnology** [comment]
> > try to install this plugin?https://github.com/UltraVanilla/cleanupstupidmojangshit/releases/tag/v1.1.0
> 
> What does it do?

See https://github.com/UltraVanilla/cleanupstupidmojangshit/blob/master/README.md

**Comment by haxbob12345** [comment]
It works! ty!
