### ISSUE TITLE
[BUG] Cant Remove 'shop' alias

### ISSUE THREAD

**Issue by tzuzn** [PotatoCraft-Studio/QuickShop-Reremake#291]
### Description

Hi,
Im using EconomyShopGUI as an adminshop and also wanted a chestshop Plugin.
I installed Quickshop and made changes to the cofing.yml.
after line 828 custom-commands: i removed the "shop" alias from the list, cause i need it for EconomyShopGUI.
If I use /shop ingame tho it still acts as an alias for qs

### Steps to reproduce

Installl EconomyShopGUI and QS
remove shop as an alias in config.yml
reload plugins (or restart server)
try to use "/shop" ingame

### Expected Behaviour

not open

### Screenshots

![grafik](https://user-images.githubusercontent.com/83777527/210677277-f1ab2731-edfd-4ad3-9039-5b302634c2ea.png)
![grafik](https://user-images.githubusercontent.com/83777527/210677352-b57315d8-2cfc-4dba-b14a-51fda264bf17.png)

### `/qs paste` URL

https://paste.helpch.at/sawasedoru

**Comment by sandtechnology** [comment]
```
#Set the command alias for qs main command
# - playershop
# - pshop
custom-commands:
```
You are not setting any value for this command, in this case, it will use default from built-in config file
You should set it to  `custom-commands: []` then restart the server to make it work
