### ISSUE TITLE
[BUG] ItemJoin Conflict

### ISSUE THREAD

**Issue by iSeitan** [PotatoCraft-Studio/QuickShop-Reremake#298]
### Description

Player can sell their ItemJoin menu

### Steps to reproduce

Create an item join with ItemJoin
Try and sell the item

### Expected Behaviour

Not be able to sell menu item

### Screenshots

![2023-01-18_09 44 42](https://user-images.githubusercontent.com/86061857/213201477-5a900779-ecb9-4d73-87c0-301399537058.png)

### `/qs paste` URL

https://paste.helpch.at/japovekanu

**Comment by sandtechnology** [comment]
Er, it shouldn't have any effect, and we have an option `blacklist-lores` for such case

**Comment by iSeitan** [comment]
The reason im opening an issue Im having a problem :)
I used the line blacklist-lores

and it didnt work
My itemjoin config
  panel:
    id: NETHER_STAR
    slot: 8
    name: '&8[&b▶&8] &f&lMenu &8[&b◀&8]'
    lore:
      - '&7Le menu'
    interact-right:
    
My qs line config
  blacklist-lores:
  - menu
  
  And player can still sell the menu item, so my question is, is there a bug or the config is not correct? :)

**Comment by sandtechnology** [comment]
> The reason im opening an issue Im having a problem :) I used the line blacklist-lores
> 
> and it didnt work My itemjoin config panel: id: NETHER_STAR slot: 8 name: '&8[&b▶&8] &f&lMenu &8[&b◀&8]' lore: - '&7Le menu' interact-right:
> 
> My qs line config blacklist-lores:
> 
>     * menu
> 
> 
> And player can still sell the menu item, so my question is, is there a bug or the config is not correct? :)

Your paste shows you haven't config it:
```
  #The list of lore keywords that are blocked from being sold.
  #This will not affect existing shops!
  blacklist-lores:
  - SoulBound
```
If you have changed it, please reply with the new paste, and I check the code and seems is okay

**Comment by iSeitan** [comment]
blacklist-lores:
  - menu
  
  My bad my paste didnt work :P

**Comment by sandtechnology** [comment]
> blacklist-lores:
> 
>     * menu
> 
> 
> My bad my paste didnt work :P
> 
> For some reason github changes the format but its the same as the default config, i just change the Soulbound to menu

You need to use /qs reload to make it effect

**Comment by sandtechnology** [comment]
Also, I need the paste link by /qs paste

**Comment by sandtechnology** [comment]
> I did, and even restarted the server with no luck, player can still sell the itemjoin item

I need the paste link by /qs paste, please provide it

**Comment by iSeitan** [comment]
https://paste.helpch.at/eyugoyiwam

**Comment by sandtechnology** [comment]
> https://paste.helpch.at/eyugoyiwam

Thanks for your information!
From the item which have put into shop, it shows no lores in there:
![image](https://user-images.githubusercontent.com/20417547/213275036-2110fb03-3c96-4cce-a62b-9ac25d10ef93.png)
So I think you can contact them for adding them as real lore in the item, for recognized by quickshop
