### ISSUE TITLE
[BUG] MCMMO Fast digging II potions showing as fast digging I

### ISSUE THREAD

**Issue by Cruwzky** [PotatoCraft-Studio/QuickShop-Reremake#305]
### Description

When use-effect-for-potion-item is true the mcmmo fast digging II potions are shown as fast digging I potions on the sign.

### Steps to reproduce

1. Set use-effect-for-potion-item to true
2. Create a shop with a mcmmo fast digging II potion
3. The sign says "Fast Digging I"

### Expected Behaviour

I would expect it to say "Fast Digging II"

### Screenshots

![2023-02-01_20 02 56](https://user-images.githubusercontent.com/20445289/216139128-441feb0c-a193-4e3f-9c2c-3d300ae4022f.png)

### `/qs paste` URL

https://paste.helpch.at/awavonufew

**Comment by sandtechnology** [comment]
``{"color":"red"
"hoverEvent":{"action":"show_item"
"value":[{"text":"{Count:1b
id:\"minecraft:potion\"
tag:{CustomPotionColor:14270531
CustomPotionEffects:[{Ambient:1b
Amplifier:1b
Duration:1800
Id:3b
ShowIcon:1b
ShowParticles:1b}]
Potion:\"minecraft:empty\"
display:{Name:\u0027{\"extra\":[{\"text\":\"Potion Of Haste II\"}]
\"text\":\"\"}\u0027}}}"}]}```
In the paste I see it actually is fast digging I, what about the information shows in tooltip?

**Comment by Cruwzky** [comment]
The tooltip is showing haste 2, I have recorded a video showing the problem: https://www.youtube.com/watch?v=GmDovZ2iTR0

**Comment by sandtechnology** [comment]
Sorry for the late reply, this snapshot should fix this problem, you can try that out: https://ci.codemc.io/job/PotatoCraft-Studio/job/QuickShop-Reremake-SNAPSHOT/2466/artifact/target/QuickShop.jar

**Comment by sandtechnology** [comment]
Fixed in 5.1.2.0 release
