### ISSUE TITLE
[BUG] Circular dependencies for ArmShopBridge 

### ISSUE THREAD

**Issue by Kingie07** [PotatoCraft-Studio/QuickShop-Reremake#316]
### Description

New Paperspigot update causes Quckshop and ArmShopBridge dependancy issues.

[13:12:08 ERROR]: [ConfiguredOrderedProviderStorage] Circular dependencies detected!
&gt; [13:12:08 ERROR]: [ConfiguredOrderedProviderStorage] You have a plugin that is depending on a plugin which refers back to that plugin. Your server will shut down until these are resolved, or the strategy is changed.
&gt; [13:12:08 ERROR]: [ConfiguredOrderedProviderStorage] Circular dependencies:
&gt; [13:12:08 ERROR]: [ConfiguredOrderedProviderStorage] QuickShop depends on ArmShopBridge depends on QuickShop...
&gt; [13:12:08 ERROR]: [ConfiguredOrderedProviderStorage] If you would like to still load these plugins, acknowledging that there may be unexpected plugin loading issues, run the server with -Dpaper.useLegacyPluginLoading=true

https://docs.papermc.io/paper/reference/paper-plugins#cyclic-dependency-detection

### Steps to reproduce

PaperMC 1.19.3 #407
Plugins - Quckshop 5.1.1.3 & AdvancedRegionMarket Shop Bridge 1.2.5

Console Error & Server force crash

[13:12:08 ERROR]: [ConfiguredOrderedProviderStorage] Circular dependencies detected!
&gt; [13:12:08 ERROR]: [ConfiguredOrderedProviderStorage] You have a plugin that is depending on a plugin which refers back to that plugin. Your server will shut down until these are resolved, or the strategy is changed.
&gt; [13:12:08 ERROR]: [ConfiguredOrderedProviderStorage] Circular dependencies:
&gt; [13:12:08 ERROR]: [ConfiguredOrderedProviderStorage] QuickShop depends on ArmShopBridge depends on QuickShop...
&gt; [13:12:08 ERROR]: [ConfiguredOrderedProviderStorage] If you would like to still load these plugins, acknowledging that there may be unexpected plugin loading issues, run the server with -Dpaper.useLegacyPluginLoading=true

### Expected Behaviour

Change dependancy according to needs of PaperMC

https://docs.papermc.io/paper/reference/paper-plugins#cyclic-dependency-detection

### Screenshots

n/a

### `/qs paste` URL

https://paste.helpch.at/ariqicacoh.md

**Comment by Kingie07** [comment]
> 

its english :D

**Comment by sandtechnology** [comment]
Should be fixed in this snapshot build, and seems bot complain about the incomplete title?
 https://ci.codemc.io/job/PotatoCraft-Studio/job/QuickShop-Reremake-SNAPSHOT/2470/artifact/target/QuickShop-5.1.1.3-SNAPSHOT.jar

**Comment by Kingie07** [comment]
> Should be fixed in this snapshot build, and seems bot complain about the incomplete title? https://ci.codemc.io/job/PotatoCraft-Studio/job/QuickShop-Reremake-SNAPSHOT/2470/artifact/target/QuickShop-5.1.1.3-SNAPSHOT.jar

Brilliant. Tested and working fine! Thankyou

**Comment by sandtechnology** [comment]
Fixed in 5.1.2.0 release
