### ISSUE TITLE
[BUG] en-US file got updated with non-english.

### ISSUE THREAD

**Issue by mibby** [PotatoCraft-Studio/QuickShop-Reremake#318]
### Description

https://github.com/PotatoCraft-Studio/QuickShop-Reremake/commit/d10441f5e569dfb0fbac5a5af042a36cbddc525c#diff-4590dae1c9a37d125588ff18f0983df1da5fcebc06d3a7c56ad7ab60af1f640d

### Steps to reproduce

Not relevant.

### Expected Behaviour

English.

### Screenshots

Not relevant.

### `/qs paste` URL

Not relevant.

**Comment by sandtechnology** [comment]
Fixed by OTA update, thanks to @YuanYuanOwO  for revert this
