### ISSUE TITLE
[BUG] `setSignText()` problem 

### ISSUE THREAD

**Issue by twseer67875** [PotatoCraft-Studio/QuickShop-Reremake#322]
### Description

I used the following code to try to change the second line of the Sign but failed to change it

```java
                    List<ComponentPackage> sign_list = event.getShop().getSignText("zh_tw");
                    if (sign_list.get(1).getComponents().length > 1){
                        BaseComponent[] baseComponents = sign_list.get(1).getComponents();

                        String message = baseComponents[1].toPlainText();

                        TextComponent textComponent = new TextComponent(message + " §4(購買限制)");

                        BaseComponent[] newBaseComponents = {
                                baseComponents[0],
                                textComponent
                        };

                        ComponentPackage componentPackage = new ComponentPackage(newBaseComponents);

                        sign_list.set(1, componentPackage);

                        event.getShop().setSignText(sign_list);
                    }
```

### Steps to reproduce

1. Use `getSignText()` to get original Sign content
2. Try `setSignText()` to change Sign
3. nothing happened

### Expected Behaviour

Successfully changed the Sign and changed it to `出售 1個 §4(購買限制)` according to the following code

### Screenshots

![image](https://user-images.githubusercontent.com/70073452/224653568-200c65df-18aa-4f29-bf3c-c7da0280853e.png)

### `/qs paste` URL

https://paste.helpch.at/raw/uteyibisuz

### Additional Context

`This server is running Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25)`

**Comment by sandtechnology** [comment]
It's not the right way to change sign text, please listen to ShopSignUpdateEvent then change the sign directly

**Comment by twseer67875** [comment]
> 更改標誌文字的方式不正確，請監聽 ShopSignUpdateEvent 然後直接更改標誌

Problem solved, thanks
