### ISSUE TITLE
[BUG] "The event is Deprecated" will still be prompted when using PlayerShopClickEvent

### ISSUE THREAD

**Issue by lRENyaaa** [PotatoCraft-Studio/QuickShop-Reremake#330]
### Description

When I tried to adapt my plugin to a new version of QuickShop, I found that PlayerShopClickEvent did not work as expected.
Code: https://github.com/RenYuan-MC/QuickShopForm/blob/master/src/main/java/ren/rymc/quickshopform/QuickShopForm.java

### Steps to reproduce

1. Using PlayerShopClickEvent
2. The server prompts "the event is Deprecated"

### Expected Behaviour

PlayerShopClickEvent should not be Deprecated

### Screenshots

![image](https://user-images.githubusercontent.com/92320175/226094130-7c435d6a-1db5-4a35-a244-ca7087cfd5b8.png)

### `/qs paste` URL

https://paste.helpch.at/amehizizaf

**Comment by sandtechnology** [comment]
This notice is not sent by us, and seems paper side will thinks an deprecated event class extends by new event class still deprecated, so I do a change in this snapshot, it should no more notice again: https://ci.codemc.io/job/PotatoCraft-Studio/job/QuickShop-Reremake-SNAPSHOT/2490/

**Comment by lRENyaaa** [comment]
seems ok :D
