### ISSUE TITLE
[BUG] When opening skulkers the floating item gets stuck.

### ISSUE THREAD

**Issue by smuddgge** [PotatoCraft-Studio/QuickShop-Reremake#342]
### Description

When opening shulker shops, the floating item gets stuck inside the shulker.

### Steps to reproduce

- Create a shop with a shulker.
- Open the shop
- The floating item is now in the shulker and not on top.

### Expected Behaviour

The item should stay on top of the shulker.

### Screenshots

![2023-04-01_22 43 00 copy](https://user-images.githubusercontent.com/68658429/229315428-be9afee1-3402-49b0-9dc4-f3c37e4015cc.png)

### `/qs paste` URL

https://paste.helpch.at/utokikacac

**Comment by sandtechnology** [comment]
Works as intended, and you can click the shop sign to reset the floating item position, so is not worth for resetting shop for floating item after open/close the skulker.
