### ISSUE TITLE
[BUG] - Warning

### ISSUE THREAD

**Issue by PhoenixCodingStuff** [PotatoCraft-Studio/QuickShop-Reremake#354]
### Description

Warning in console

### Steps to reproduce

1. Download Quickshop
2. Upload Quickshop
3. Start server

### Expected Behaviour

No warning

### Screenshots

`[07:00:26] [Server thread/WARN]: [QuickShop] QuickShop detected tax account not exists, we're trying to create one. If you see any errors, please change tax-account in config.yml to server owner in-game username
[07:00:26] [Server thread/WARN]: [QuickShop] Cannot to create tax-account,  please change tax-account in config.yml to server owner in-game username
[07:00:26] [Server thread/WARN]: [QuickShop] Tax account's player never played this server before and failed to create one, that may cause server lagg or economy system error, you should change that name. But if this warning not cause any issues, you can safety ignore this.`

### `/qs paste` URL

https://paste.helpch.at/dibaqajimo

### Additional Context

Using server owner in-game username may not be useful when you as a owner yourself are playing. To fix this, if tax account's player never played on the server before and try to make fake username. If not possible give `getLogger().info` instead of `getLogger().warning` and disable the setting in config itself.

**Comment by sandtechnology** [comment]
It should be a warning because it will affect something, and as you can see we have tried that but failed, you can just set it to empty to setting no tax account but still taxing:
```
#The fake player where the tax money goes to.
#Set this to "" to disable it (Taxing will still work but not deposit to any account)
tax-account: Server
```

**Comment by sandtechnology** [comment]
> Ok thx, any idea why the tax account could not be created?

Mostly is because eco plugin does not support fake account, and we can just get the failed result and doesn't know the reason.
