### ISSUE TITLE
[BUG] java.lang.NullPointerException

### ISSUE THREAD

**Issue by daniel-skopek** [PotatoCraft-Studio/QuickShop-Reremake#357]
### Description

I'm getting NullPointerException after starting up the plugin.

Error: https://pastebin.com/raw/6xsSUFQc

### Steps to reproduce

Start the plugin.

### Expected Behaviour

There should not be any error.

### Screenshots

Provided log

### `/qs paste` URL

The file was too large

**Comment by veteranmina** [comment]
Just looking real quick on this as an outside source. YGGDRASIL is used for authenticating user credentials for minecraft. 

Is your server set to offline mode?

**Comment by sandtechnology** [comment]
It should be server software issue, please report to them
