### ISSUE TITLE
[BUG] 1.20.1,Request adaptation

### ISSUE THREAD

**Issue by welove69** [PotatoCraft-Studio/QuickShop-Reremake#362]
### Description

Request adaptation,1.20.1

### Steps to reproduce

1.20.1,Unusable

### Expected Behaviour

Request adaptation,1.20.1

### Screenshots

WARN

### `/qs paste` URL

WARN

**Comment by sandtechnology** [comment]
Close this issue due to is not a bug and you can just use snapshot, it should support 1.20 now: https://ci.codemc.io/job/PotatoCraft-Studio/job/QuickShop-Reremake-SNAPSHOT/
