### ISSUE TITLE
residence intercepts signs where players interact with QuickShop

### ISSUE THREAD

**Issue by welove69** [PotatoCraft-Studio/QuickShop-Reremake#367]
### Description

residence intercepts signs where players interact with QuickShop
Is there a way to fix it?

QuickShop 5.1.2.1
Residence 5.1.2..

### Steps to reproduce

residence intercepts signs where players interact with QuickShop

### Expected Behaviour

Billboards can be interactive

### Screenshots

Signage is intercepted by residential interactions

### `/qs paste` URL

Signage is intercepted by residential interactions

**Comment by sandtechnology** [comment]
There is no way to fix since it's the protection plugin block it, please give the permission it needed
