### ISSUE TITLE
[BUG] LWCX not restored after deletion of shop via control panel

### ISSUE THREAD

**Issue by mrfloris** [PotatoCraft-Studio/QuickShop-Reremake#38]
### Description

Using `/shops removeall` the lwcx info is on the shop again, if a player placed a chest, made a shop and we later remove it all.

However, when the player makes a shop, then right clicks and clicks on remove, it turns into a regular public chest, lwcx is no longer respected. Many will forget this and other players can steal from the chest. 

lwcx integration is set to true.

### Steps to reproduce

However, when the player makes a shop, then right clicks and clicks on remove, it turns into a regular public chest, lwcx is no longer respected. Many will forget this and other players can steal from the chest. 

### Expected Behaviour

that /cinfo shows the chest is still registered as before, kinda like how show removeall does it.

### Screenshots

<img width="1512" alt="Screenshot 2021-12-20 at 03 45 14" src="https://user-images.githubusercontent.com/28841349/146704482-90ba0254-c4f2-4789-bdfb-560efaa585c9.png">

### `/qs paste` URL

n/a

### Additional Context

```
Server:
	Name: Paper
	Server Name: Paper
	Build: git-Paper-79 (MC: 1.18.1)
	NMSV: v1_18_R1
	Data Version: 2865
	Java: 17.0.1
```
```
QuickShop:
	Version: 5.1.0.2
	Fork: Reremake
	Build Number: 125
	Build Branch: origin/release
	Build Commit: 1cafc4a92503e1ace0506c52c8ee9aeb828e2881
	Build URL: https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake/125/
	Build Tag: 125
	Chat System: Hardcoded Adventure
	Server ID: 4f84c78a-c38b-497e-acc7-fe520b4dc4eb
	OpenInv Hook: Disabled
	Economy System: Vault%CMIEconomy
```
```
LWC @ Enabled # 2.2.8-dev-52b334e # 1.13 # com.griefcraft.lwc.LWCPlugin
```
```
  #If you have LWC/LWCX, QuickShop will check access.
  LWC: true
```

**Comment by sandtechnology** [comment]
I have check the code, it should remove LWC protection when shop created (when protection-checking is enabled, it will fire a fake blockbreakevent, let lwc think the chest was broken and remove the protection), prevent conflicting with this plugin when interacting, also removeall and remove command did the same thing, so the shop persisted protection should be the protection created after shop created.
Maybe a warning message should be added for warning this

**Comment by sandtechnology** [comment]
If you just have LWC as protection plugin or other installed protection plugin have built-in integration, you can use that then disable `protection-checking` for a workaround.

**Comment by Ghost-chu** [comment]
closed: no response

**Comment by mrfloris** [comment]
> closed: no response

Sorry .. 

After review we've moved away from using this plugin, it has too many situations where people can take items, abuse a situation, .. at least for the way that we deal with our world, region, chest, player protection. Smeths was able to rebuild ShopChest for us for 1.18.1 so we're sticking with that until the situation comes up again where we try to find a solution. Hopefully by then lwcx and other types of things that we consider an issue are approached in a way that doesn't bring us those risks. 

I like this plugin though. But every server is different and we're looking for something that fits in our puzzle of a setup.
