### ISSUE TITLE
[BUG] QuickShop remake can not load use linux 

### ISSUE THREAD

**Issue by Alex9315** [PotatoCraft-Studio/QuickShop-Reremake#390]
### Description

[BUG] QuickShop remake can not load use linux when I use windows thats alright
[BUG] QuickShop remake can not load use linux when I use windows thats alright
Im sure my plugin is not Malware and on windows system I can use that correctly

### Steps to reproduce

[BUG] QuickShop remake can not load use linux when I use windows thats alright
[BUG] QuickShop remake can not load use linux when I use windows thats alright
Im sure my plugin is not Malware and on windows system I can use that correctly

### Expected Behaviour

fix verfiy of plugin or delete it,,,,,,,
[BUG] QuickShop remake can not load use linux when I use windows thats alright
Im sure my plugin is not Malware and on windows system I can use that correctly

### Screenshots

[spoider][15:10:43] [Server thread/WARN]: [QuickShop] >> Modified Class Detected <<[15:10:43] [Server thread/WARN]: [QuickShop] Name: org/maxgamer/quickshop/QuickShop.class[15:10:43] [Server thread/WARN]: [QuickShop] CRC: 1918548895[15:10:43] [Server thread/WARN]: [QuickShop] ALERT: QuickShop cannot validate itself. This may be caused by you having deleted QuickShop's jar while the server is running.java.lang.reflect.InaccessibleObjectException: Unable to make field private java.lang.String java.util.jar.JarFile$JarFileEntry.basename accessible: module java.base does not "opens java.util.jar" to unnamed module @f704721        at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354) ~[?:?]        at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[?:?]        at java.lang.reflect.Field.checkCanSetAccessible(Field.java:178) ~[?:?]        at java.lang.reflect.Field.setAccessible(Field.java:172) ~[?:?]        at com.google.gson.internal.reflect.UnsafeReflectionAccessor.makeAccessible(UnsafeReflectionAccessor.java:44) ~[gson-2.8.9.jar:?]        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:159) ~[gson-2.8.9.jar:?]        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102) ~[gson-2.8.9.jar:?]        at com.google.gson.Gson.getAdapter(Gson.java:489) ~[gson-2.8.9.jar:?]        at com.google.gson.Gson.toJson(Gson.java:727) ~[gson-2.8.9.jar:?]        at com.google.gson.Gson.toJson(Gson.java:714) ~[gson-2.8.9.jar:?]        at com.google.gson.Gson.toJson(Gson.java:669) ~[gson-2.8.9.jar:?]        at com.google.gson.Gson.toJson(Gson.java:649) ~[gson-2.8.9.jar:?]        at org.maxgamer.quickshop.util.envcheck.EnvironmentChecker.lambda$securityVerify$2(EnvironmentChecker.java:232) ~[?:?]        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]        at org.maxgamer.quickshop.util.envcheck.EnvironmentChecker.securityVerify(EnvironmentChecker.java:227) ~[?:?]        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]        at org.maxgamer.quickshop.util.envcheck.EnvironmentChecker.run(EnvironmentChecker.java:123) ~[?:?]        at org.maxgamer.quickshop.QuickShop.runtimeCheck(QuickShop.java:866) ~[?:?]        at org.maxgamer.quickshop.QuickShop.onEnable(QuickShop.java:958) ~[?:?]        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:525) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3579-Spigot-e53686f-dd0a218]        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:439) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3579-Spigot-e53686f-dd0a218]        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:584) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3579-Spigot-e53686f-dd0a218]        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:403) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3579-Spigot-e53686f-dd0a218]        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:255) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3579-Spigot-e53686f-dd0a218]        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:968) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3579-Spigot-e53686f-dd0a218]        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:293) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3579-Spigot-e53686f-dd0a218]        at java.lang.Thread.run(Thread.java:833) [?:?][15:10:43] [Server thread/WARN]: [QuickShop] [FATAL] Signature Verify: Failed to validate digital signature! Security may be compromised![15:10:43] [Server thread/ERROR]: [QuickShop] [Security Risk Detected] QuickShop forcing crash the server for security, contact the developer for details.[15:10:43] [Server thread/WARN]: [QuickShop] [Security Risk Detected] To get more details, please check: file:/home/Server/F%20Survival/Survival/plugins/QuickShop/ddb1719c-a66d-4c37-9c75-54bdb2208c7d.security.letter.txt>[/SPOIDER]
--

</body>
</html>

### `/qs paste` URL

https://paste.helpch.at/

### Additional Context

[BUG] QuickShop remake can not load use linux when I use windows thats alright
Im sure my plugin is not Malware and on windows system I can use that correctly

**Comment by XiaMoHuaHuo-CN** [comment]
Try add a flag to skip the signature check.

**Comment by Alex9315** [comment]
> Try add a flag to skip the signature check.

hummm how can  I do that？

**Comment by sandtechnology** [comment]
it's not related to which system you are using, instead, that file (our plugin jar) is being modified and detected by java or our self checking system, please do a virus check or just open the jar by archiver software after redownload the jar from server and check which file it added

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
