### ISSUE TITLE
Wg bug

### ISSUE THREAD

**Issue by ghost** [PotatoCraft-Studio/QuickShop-Reremake#393]
### Description

Bugged integration and / or misleading error message.

### Steps to reproduce

Download plugin and wg.
Add to your server.
Configure.
Create region.
Configure flags.
Start your server.
Try to create shop.

### Expected Behaviour

Create the shop or give a proper error message.

### Screenshots

https://media.discordapp.net/attachments/1112273037807591505/1147212325749792850/Screenshot_2023-09-01-22-21-45-219-edit_com.android.chrome.jpg

https://media.discordapp.net/attachments/1112273037807591505/1147214082651455579/Screenshot_2023-09-01-22-29-00-225-edit_com.android.chrome.jpg

https://media.discordapp.net/attachments/1074746943630217324/1147206510028529755/image.png

You can check the config from the paste link I sent 👇

### `/qs paste` URL

https://paste.helpch.at/emivuhuhak

### Additional Context

N/A

**Comment by YuanYuanOwO** [comment]
Just disable `protection-checking` and use worldguard integration (enable whitelist and only use flag permission, you will need to restart the server) would be okay
