### ISSUE TITLE
[BUG] AdvancedRegionMarket integration doesn't work

### ISSUE THREAD

**Issue by Bloodlex** [PotatoCraft-Studio/QuickShop-Reremake#395]
### Description

After expiring the region, advancedregionmarket integration doesn't delete shops.

### Steps to reproduce

1. Create an ARM region with shops.
2. Expire or unsell the region.
3. Shops are still there although integration is enabled.

### Expected Behaviour

Shops should be deleted.

### Screenshots

None

### `/qs paste` URL

https://paste.helpch.at/bahurileya

### Additional Context

None

**Comment by sandtechnology** [comment]
https://ci.codemc.io/job/PotatoCraft-Studio/job/QuickShop-Reremake-SNAPSHOT/2539/artifact/target/QuickShop-5.1.2.3-SNAPSHOT.jar
This build should fix it
