### ISSUE TITLE
[BUG] Buy item but dont recieve- money is taken but item isn't given

### ISSUE THREAD

**Issue by Draesia** [PotatoCraft-Studio/QuickShop-Reremake#42]
### Description

Creating a shop with a damaged item, and then stocking with a fully repaired item- shows that the shop has stock.

When the player buys from this shop, money is taken- but the item isn't given.

### Steps to reproduce

1. Create a shop for some enchanted Iron Leggings which have been around half way damaged.
2. Stock the shop with the same enchants for the leggings, but fully repaired
3. Have a player purchase from the shop
4. Money is given to the owner, and no item is given to the player 

### Expected Behaviour

Quickshop should give the item in the chest to the player, or not allow creating shops with damaged items at all.

### Screenshots

Not required.

### `/qs paste` URL

https://paste.helpch.at/voyocesege

**Comment by swagninjanotgirl** [comment]
agreed

**Comment by sandtechnology** [comment]
https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/2088/ Should fix it

**Comment by sandtechnology** [comment]
The fixes in PR will result the same issue right there, please test if this snapshot also fix this issue as well:
https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/2125/

**Comment by sandtechnology** [comment]
Look like the PR actually fix unfair comparing but not this issue, revert reverted fixes snapshot is there: https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/2127/

**Comment by Draesia** [comment]
Nice find!

I will test when I am able :D

**Comment by sandtechnology** [comment]
I have fixed this issue again for unfair-comparing, if you still haven't a test you can use the latest RC version: https://ci.codemc.io/job/PotatoCraft-Studio/job/QuickShop-Reremake-SNAPSHOT/2149/

**Comment by Ghost-chu** [comment]
fixed in 5.1.0.3
