### ISSUE TITLE
[BUG] Display Items Flying Off

### ISSUE THREAD

**Issue by Caroline4747** [PotatoCraft-Studio/QuickShop-Reremake#444]
### Description

When you have a shulker chest shop facing up and open it the display hologram flings away

### Steps to reproduce

1. Make a chest shop, using a Shulker box placed on the ground as usual
2. Open the Shulker (to restock etc)
3. Floating icon flies off to the side

### Expected Behaviour

Not fling the display item

### Screenshots

<img width="556" alt="Screenshot 2024-01-25 at 2 01 50 PM" src="https://github.com/PotatoCraft-Studio/QuickShop-Reremake/assets/127627259/2215c398-1e9c-438f-94cf-bf2bdb9f5ed2">
<img width="821" alt="Screenshot 2024-01-25 at 2 02 14 PM" src="https://github.com/PotatoCraft-Studio/QuickShop-Reremake/assets/127627259/4675d0e4-e223-4417-8fcd-12558542d373">

### `/qs paste` URL

https://paste.helpch.at/kibepasaxa

**Comment by sandtechnology** [comment]
There are nothing we can do there, the virtual item just appear in client so every player will see the different behavior for the same shop display item, and we can't handle that expect a additional packet to teleport it.
