### ISSUE TITLE
[BUG] Unable to run in 1.20.6 version

### ISSUE THREAD

**Issue by suoxiaojun** [PotatoCraft-Studio/QuickShop-Reremake#475]
### Description

The PaperMC team has added PluginRemapper in the new version of the core, which will remapper the Plugin jar file when the server is started. After Remapper is completed, QuickShop reports a Security Report, which prevents this plugin from running on 1.20.6
I can guarantee that I downloaded the jar from the Spigot official page, page link https://www.spigotmc.org/resources/quickshop-reremake-1-20-2-ready-multi-currency.62575/

Error:
  QuickShop Security Report
=============================
Description:
    QuickShop detected self jar has been modified.
    Learn more: https://github.com/PotatoCraft-Studio/QuickShop-Reremake/wiki/QuickShop-halt-my-server

What that mean: 
    It usually mean the jar has been infected by malware and cannot be trusted.
    Make sure you downloading jar from our SpigotMC and CodeMC pages.
    Any other sources is untrusted and may provide a infected jar.

I download QuickShop from SpigotMC, why I still see this:
    As far as we know, some malware like "L10" have ability to infect other jars that installed on your server.
    So clean jar can be infect when you installed on infected server.

What should I do:
    Backup your server immediately, execute virus scan with regular anti-malware software and Spigot Anti-Malware tool.
    You can download SAMT here: https://www.spigotmc.org/resources/spigot-anti-malware.64982/

Could this be a false positive:
    Basically not.

I need some help to handle this issue:
    Our community and developer can help you and give you action suggestion.
    Join our discord support server: https://discord.gg/bfefw2E

Can I disable this noisy check:
    No, you can't.

----------------------------------
Important information related to this issue.
When you ask for support, please provide this paste to the support staffs:

META-INF signature missing: name=META-INF/SELFSIGN.DSA
META-INF signature missing: name=META-INF/SELFSIGN.SF

### Steps to reproduce

Using Paper or Purpur 1.20.6 build and running server...

### Expected Behaviour

Support 1.20.6 or 1.20.1 versions

### Screenshots

META-INF signature missing: name=META-INF/SELFSIGN.DSA
META-INF signature missing: name=META-INF/SELFSIGN.SF

### `/qs paste` URL

Nothing

### Additional Context

As my English is not very good, I am using a translator. If there is any offense, please forgive me. Thank you
Java Version: "22.0.1" 2024-04-16
Java(TM) SE Runtime Environment (build 22.0.1+8-16)
Java HotSpot(TM) 64-Bit Server VM (build 22.0.1+8-16, mixed mode, sharing)
Windows 8.1
Plugin Version: 5.1.2.5

**Comment by YuanYuanOwO** [comment]
你可以使用 DeepL 翻译，参考该Issue #468

**Comment by Rebines** [comment]
> 你可以使用 DeepL 翻译，参考该Issue #468

https://ghost-chu.github.io/QuickShop-Hikari-Documents/docs/addon/reremake-migrator 这个地址发生错误，无法正确转换QuickShop Hikari并弹出错误”[15:41:44 WARN]: [QuickShop-Hikari] [WARN] Virtual DisplayItem Support Test: VirtualDisplayItemManager is null, this shouldn't happen, contact with QuickShop-Hikari developer.“
![image](https://github.com/user-attachments/assets/b306cf8d-7576-45d2-946c-67acfb44c11c)

**Comment by YuanYuanOwO** [comment]
> > 你可以使用 DeepL 翻译，参考该Issue #468
> 
> https://ghost-chu.github.io/QuickShop-Hikari-Documents/docs/addon/reremake-migrator 这个地址发生错误，无法正确转换QuickShop Hikari并弹出错误”[15:41:44 WARN]: [QuickShop-Hikari] [WARN] Virtual DisplayItem Support Test: VirtualDisplayItemManager is null, this shouldn't happen, contact with QuickShop-Hikari developer.“ ![image](https://private-user-images.githubusercontent.com/97930336/348457862-b306cf8d-7576-45d2-946c-67acfb44c11c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NTc0MTAsIm5iZiI6MTcyMDg1NzExMCwicGF0aCI6Ii85NzkzMDMzNi8zNDg0NTc4NjItYjMwNmNmOGQtNzU3Ni00NWQyLTk0NmMtNjdhY2ZiNDRjMTFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEzVDA3NTE1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjYmJlYzIyMzA4Njk0MGUwMWNkMzNlNjYzMWIyMjVmOWU2MzVlZTZmZDNmMmY5MTM4NGJkODZkNjFjYjJjNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IrpvmqbvyPtcN6OErpG8WPPguV-bgVuCD69UGk3_r2E)

链接访问失败为已知问题，正在等待修复。 
https://github.com/QuickShop-Community/QuickShop-Hikari-Documents/blob/master/docs/addon/reremake-migrator.md 
这里是原文页面
不行就去 Discord 频道发个消息，我来帮你转换（

**Comment by Rebines** [comment]
> > > 你可以使用 DeepL 翻译，参考该Issue #468
> > 
> > 
> > https://ghost-chu.github.io/QuickShop-Hikari-Documents/docs/addon/reremake-migrator 这个地址发生错误，无法正确转换QuickShop Hikari并弹出错误”[15:41:44 WARN]: [QuickShop-Hikari] [WARN] Virtual DisplayItem Support Test: VirtualDisplayItemManager is null, this shouldn't happen, contact with QuickShop-Hikari developer.“ ![image](https://private-user-images.githubusercontent.com/97930336/348457862-b306cf8d-7576-45d2-946c-67acfb44c11c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NTc0MTAsIm5iZiI6MTcyMDg1NzExMCwicGF0aCI6Ii85NzkzMDMzNi8zNDg0NTc4NjItYjMwNmNmOGQtNzU3Ni00NWQyLTk0NmMtNjdhY2ZiNDRjMTFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEzVDA3NTE1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjYmJlYzIyMzA4Njk0MGUwMWNkMzNlNjYzMWIyMjVmOWU2MzVlZTZmZDNmMmY5MTM4NGJkODZkNjFjYjJjNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IrpvmqbvyPtcN6OErpG8WPPguV-bgVuCD69UGk3_r2E)
> 
> 链接访问失败为已知问题，正在等待修复。 https://github.com/QuickShop-Community/QuickShop-Hikari-Documents/blob/master/docs/addon/reremake-migrator.md 这里是原文页面 不行就去 Discord 频道发个消息，我来帮你转换（

问题是我不在那个频道里呀）

**Comment by YuanYuanOwO** [comment]
> > > > 你可以使用 DeepL 翻译，参考该Issue #468
> > > 
> > > 
> > > https://ghost-chu.github.io/QuickShop-Hikari-Documents/docs/addon/reremake-migrator 这个地址发生错误，无法正确转换QuickShop Hikari并弹出错误”[15:41:44 WARN]: [QuickShop-Hikari] [WARN] Virtual DisplayItem Support Test: VirtualDisplayItemManager is null, this shouldn't happen, contact with QuickShop-Hikari developer.“ ![image](https://private-user-images.githubusercontent.com/97930336/348457862-b306cf8d-7576-45d2-946c-67acfb44c11c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NTc0MTAsIm5iZiI6MTcyMDg1NzExMCwicGF0aCI6Ii85NzkzMDMzNi8zNDg0NTc4NjItYjMwNmNmOGQtNzU3Ni00NWQyLTk0NmMtNjdhY2ZiNDRjMTFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEzVDA3NTE1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjYmJlYzIyMzA4Njk0MGUwMWNkMzNlNjYzMWIyMjVmOWU2MzVlZTZmZDNmMmY5MTM4NGJkODZkNjFjYjJjNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IrpvmqbvyPtcN6OErpG8WPPguV-bgVuCD69UGk3_r2E)
> > 
> > 
> > 链接访问失败为已知问题，正在等待修复。 https://github.com/QuickShop-Community/QuickShop-Hikari-Documents/blob/master/docs/addon/reremake-migrator.md 这里是原文页面 不行就去 Discord 频道发个消息，我来帮你转换（
> 
> 问题是我不在那个频道里呀）

那你就加啊（  
https://discord.gg/Bu3dVtmsD3
