### ISSUE TITLE
[Bug] Shop Creation can happened for destroyed old chest

### ISSUE THREAD

**Issue by thunderlight411** [PotatoCraft-Studio/QuickShop-Reremake#51]
### Description

When a player want to remove a chest with any tool he gets the messages to enter a price in chat to set a sell price.
This happens to old (longer than a month) and new chests.

After destroying the chest chat is still locked in for a currency to be set.
If chest is broken the first messages will be canceled with the messages the chest was removed.

### Steps to reproduce

Place a chest and remove it it.

### Expected Behaviour

Only the first few seconds / minutes after a chest is placed to enable a shop on a chest.
When older then certain time it will be canceled as a shop and act like a regular chest even if the chest is hit with a item.

### Screenshots

![Uploading 2021-12-29_11.58.34.png…]()

### `/qs paste` URL

https://paste.helpch.at/ufikuzewal

**Comment by sandtechnology** [comment]
There have a meme image for this behavior:
![image](https://user-images.githubusercontent.com/20417547/147664036-d0ca349a-90c5-4cfa-966a-e8043ad4ef70.png)

Anyway, this should be a enhancement instead of a bug

**Comment by sandtechnology** [comment]
How about this build? https://ci.codemc.io/job/Ghost-chu/job/QuickShop-Reremake-SNAPSHOT/2101/
