### ISSUE TITLE
[BUG] Players without permission for /qs removeall can see the command with /qs help

### ISSUE THREAD

**Issue by SrBedrock** [PotatoCraft-Studio/QuickShop-Reremake#71]
### Description

Players without permission for `/qs removeall` can see the command with `/qs help`

### Steps to reproduce

1. Remove `quickshop.removeall`, `quickshop.removeall.self` and `quickshop.removeall.others`  from players.

2. Use `/qs help`

### Expected Behaviour

Players do not see command descriptions that they do not have permission.

### Screenshots

![image](https://user-images.githubusercontent.com/51332006/150298367-405f324a-401d-4d32-a4bf-3d5a24418256.png)

### `/qs paste` URL

https://paste.helpch.at/ofujihuzeg

**Comment by sandtechnology** [comment]
https://ci.codemc.io/job/PotatoCraft-Studio/job/QuickShop-Reremake-SNAPSHOT/2181/
How about this version?

**Comment by SrBedrock** [comment]
> [ci.codemc.io/job/PotatoCraft-Studio/job/QuickShop-Reremake-SNAPSHOT/2181](https://ci.codemc.io/job/PotatoCraft-Studio/job/QuickShop-Reremake-SNAPSHOT/2181/) How about this version?

Solved with https://github.com/PotatoCraft-Studio/QuickShop-Reremake/commit/bf32c689d00464de8e1609f381893ead915b0ccc

![image](https://user-images.githubusercontent.com/51332006/150406157-65e171af-b8d7-410c-b5f8-9d0227c228af.png)
