### ISSUE TITLE
[BUG]  Add some mod items got ERROR

### ISSUE THREAD

**Issue by lovefxyo** [PotatoCraft-Studio/QuickShop-Reremake#73]
### Description

When I use /qs create to add some mod items ,the shop create successfully but with a warning error at game, and the server console got  ERROR logs too. And the players can't bug these things from the shop.

### Steps to reproduce

1. Hold the mod items on hand.
2. /qs create 200
3. Got error.

### Expected Behaviour

Could you find why it appear ,and could you fix it to fit all the mod items?

### Screenshots

![DD7683FAE04370D99632BD3FF742C1A7](https://user-images.githubusercontent.com/52705605/150394550-74455d2e-3fd2-40f6-b810-a559b389de38.png)

### `/qs paste` URL

https://paste.helpch.at/rarejugawi.cs

**Comment by Ghost-chu** [comment]
unsupported server software.
Forge/Fabric/Sponge modded.

**Comment by lovefxyo** [comment]
Thanks a lot for repeating me so fast. Do you mean that Forge mods are not support?

**Comment by Ghost-chu** [comment]
> Thanks a lot for repeating me so fast. Do you mean that Forge mods are not support?

We don't support hybrid server (CatServer, Magma, Mohist, LoliServer, Sponge, etc.)
