### ISSUE TITLE
[BUG] Tax setting not working

### ISSUE THREAD

**Issue by Shpries** [PotatoCraft-Studio/QuickShop-Reremake#74]
### Description

I have set **tax** in config.yml to 0.05,but when I test it using 2 accounts in my test server,I found there's no tax deposited.I feel strange but it does happen.

### Steps to reproduce

1.Set tax value,save config and restart server
2.Join the game
3.Buy an item for X coins
4.The seller got X coins,no tax deposited

### Expected Behaviour

Tax deposited correctly as the user set.

### Screenshots

![pic1](https://s2.loli.net/2022/01/21/NSuJLYTykinGzPg.png)
![pic2](https://s2.loli.net/2022/01/21/MmQubZYpDrVnoKh.png)
![pic3](https://s2.loli.net/2022/01/21/sXhHmUJ8BpuxYFN.png)

### `/qs paste` URL

https://paste.helpch.at/agohozubah

**Comment by Ghost-chu** [comment]
try reproduce the issue before create the paste.

you must create paste immediately after reproduce it

**Comment by Shpries** [comment]
> 

https://paste.helpch.at/ficawebuno

**Comment by sandtechnology** [comment]
Tax setting working but the displaying the wrong value, should fixed in this version: https://ci.codemc.io/job/PotatoCraft-Studio/job/QuickShop-Reremake-SNAPSHOT/2185/

**Comment by Ghost-chu** [comment]
closed: no response
