### ISSUE TITLE
[BUG] Seller gets notified in buyers language

### ISSUE THREAD

**Issue by TamrielNetwork** [PotatoCraft-Studio/QuickShop-Reremake#75]
### Description

Player gets notified in buyers/sellers language when they buy/sell at their shop.

### Steps to reproduce

1. Have a player join with different language than default
2. Have him buy sth in your shop (your language is english)

### Expected Behaviour

1. Get notified in your language

### Screenshots

[Screenshot](https://i.imgur.com/SYkL618.jpg)

### `/qs paste` URL

https://paste.helpch.at/osukefuxuz

### Additional Context

Your Bugreport template is awesome :)

**Comment by sandtechnology** [comment]
How about this version? https://ci.codemc.io/job/PotatoCraft-Studio/job/QuickShop-Reremake-SNAPSHOT/2190/

**Comment by TamrielNetwork** [comment]
I will lyk tomorrow. Cant test it right now. Thanks for the patch tho!

**Comment by TamrielNetwork** [comment]
Seems like the bug is fixed. The player encountering it didn't notice any more notifications in a different language.
However I can't tell for certain, since I'm not sure if many people with their game in German bought in his shop today.
Pretty sure it's fixed tho. If not, I will reopen this.
Thanks for the help!
