### ISSUE TITLE
[BUG] Plugin Conflict

### ISSUE THREAD

**Issue by lvp12345** [PotatoCraft-Studio/QuickShop-Reremake#83]
### Description

So I ran into an issue with sign selection and with the help of a mod on discord tracked it down to a specific plugin/lib conflict. Not sure which end to try and get help on getting these compatible so I am putting in this request on yours and the other plugin.

### Steps to reproduce

Add in itemsadder v2.55 + Lonelibs v1.0.16b - 1.18.1 compatibility + ProtocolLib v4.7.0, issue happens generally every 1 in 3 sign selections it will interact with a previous sign instead of the one you click on that shows in chat.

### Expected Behaviour

n/a

### Screenshots

https://www.dropbox.com/s/stxgo63hbp5851y/Untitled%201.avi?dl=0

### `/qs paste` URL

https://paste.helpch.at/guyijazoni

### Additional Context

I know this is not directly an issue with you guys, but yours is the best sign shop plugin I have found and is incredibly valuable to me for my server. If there is any way this can be made compatible or if there is anything more I can give to help with this let me know.

Thank you for looking into this issue for me

**Comment by Ghost-chu** [comment]
```yaml
  protection-checking-listener-blacklist:
    - @ItemAdder
    - @Lonelibs
```
in older version, you also need switch to QuickShop event bus.

**Comment by lvp12345** [comment]
the above doesn't fix the issue at all sadly

**Comment by Ghost-chu** [comment]
reasonable, this only used for protection checks, doesn't work for interact
