### ISSUE TITLE
[BUG] There is a sentence that does not disappear from the help.

### ISSUE THREAD

**Issue by goddy516** [PotatoCraft-Studio/QuickShop-Reremake#86]
### Description

I disabled "quickshop.removeall" in permission, but it doesn't disappear from help.

### Steps to reproduce

Run "lp group default permission set quickshop.removeall false" in LuckPerms.
The explanation of removeall has not disappeared from the help displayed by executing "/qs".

### Expected Behaviour

"Remove all" disappears from the help.

### Screenshots

none

### `/qs paste` URL

https://paste.helpch.at/zaponuwana

**Comment by Ghost-chu** [comment]
https://github.com/PotatoCraft-Studio/QuickShop-Reremake/issues/71
