### ISSUE TITLE
[Feature request] Buy and sell from the same barrel

### ISSUE THREAD

**Issue by Bloodlex** [PotatoCraft-Studio/QuickShop-Reremake#89]
### Description

**ATTENTION: I CAN'T ADD A NEW FEATURE REQUEST (link broken, and old discussion only read-only)**

As of 1.18.1 a lot of chests cause FPS drop on client's side, we decided to move to barrels instead. We use Purpur to enchance barrels to contain 6 rows (exactly like double chests). It works like a charm with exception for one feature: buying and selling to the same container in the same time (like you can do with double chests by placing two shop signs on both basic parts of that chest).

Is there any way it could be also enabled for a barrel? Perhaps it is possible to place two barrels next to each other and link them in some way? or attach a second sign from another side of a barrel?

Thanks for your attention.

### Steps to reproduce

none

### Expected Behaviour

none

### Screenshots

none

### `/qs paste` URL

https://example.com

### Additional Context

none

**Comment by Ghost-chu** [comment]
double chest support provided by Bukkit, we actually didn't dedicated to supporting it.

**Comment by Ghost-chu** [comment]
Work in prograss in Apollo branch.
No ETA can provide.

**Comment by Bloodlex** [comment]
> Work in prograss in Apollo branch. No ETA can provide.

Thanks! 🙂

**Comment by Ghost-chu** [comment]
alright, I have tried add this feature but it looks really hard.

if I want to impl the duo shop in same container, that mean a shop multiple shop-type in this momoent and that also mean multiple price can exists in same time.

and that also mean the operation will be complex if i do so, the QuickShop will no-longer "Quick" and "Easy to use". that it's not what i hope
