### ISSUE TITLE
[BUG] 在领地内创建商店需要destory权限

### ISSUE THREAD

**Issue by Aira-Sakuranomiya** [PotatoCraft-Studio/QuickShop-Reremake#91]
### Description

此时我希望玩家可以在领地内创建商店但是不可以破坏商店设施，已经给予了玩家use权限

### Steps to reproduce

1. 打开Residence支持
2. 已给予玩家use权限
3. 玩家创建商店时提示没有destory权限

### Expected Behaviour

此时应当是可以创建商店的...

### Screenshots

![2022-02-07_22 28 00](https://user-images.githubusercontent.com/45261195/152807033-adb03fcc-5ca8-4273-a1d1-944943988245.png)

### `/qs paste` URL

https://paste.helpch.at/epupubisop

**Comment by YuanYuanOwO** [comment]
尝试在配置文件里禁用 protection-checking 呢

**Comment by Ghost-chu** [comment]
QuickShop required break permission to create the shop.
