### ISSUE TITLE
[BUG] Error when trying to sell renamed heads

### ISSUE THREAD

**Issue by SrBedrock** [PotatoCraft-Studio/QuickShop-Reremake#94]
### Description

Error when trying to sell renamed heads
Error: https://gist.github.com/SrBedrock/8034788e76b8201f829844e9db948d84

### Steps to reproduce

1. Create a store with a renamed head;
2. Try to buy the custom head in the store;
3. No error or message is sent in the buyer's chat and the purchase is not made.

### Expected Behaviour

1. Create a store with a renamed head;
2. Try to buy the custom head in the store;
3. Buy the custom head in the store.

### Screenshots

Shop Panel:
![image](https://user-images.githubusercontent.com/51332006/152878289-3a01a38f-8889-4a9e-8d2d-721fca6b1c28.png)

Shop Preview:
![image](https://user-images.githubusercontent.com/51332006/152878323-f9aa63c8-025c-4b4e-9627-19251f767d6b.png)

Shop Item:
![image](https://user-images.githubusercontent.com/51332006/152878333-01b81250-f3a2-46b9-876b-67177d4de088.png)

Item Debug:
`{display: {Name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"green","text":"[Ajudante] "},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#1B00A6","text":"B"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#3700A2","text":"l"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#49009F","text":"a"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#56009B","text":"c"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#610098","text":"k"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#70009E","text":"B"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#7F01A4","text":"i"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#8E02A9","text":"r"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#A803B9","text":"d"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#C203C8","text":"x"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#DD02D6","text":"1"}],"text":""}'}, SkullOwner: {Name: "BlackBirdx1", Properties: {textures: [{Value: "ewogICJ0aW1lc3RhbXAiIDogMTYwODMzNjg1NzgwMSwKICAicHJvZmlsZUlkIiA6ICI5MDk3ZjJlZmNkYWU0YzhlOGU0NTJiMjIxMDc3NDdmMCIsCiAgInByb2ZpbGVOYW1lIiA6ICJmb2tzZXoiLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvY2RlZmI5ZWZjNTUyN2RlODE0Y2NhZWMwM2FlYWMyYTA5YTE5Y2U2OGMwMDBhNjhkNGZkMTJjMTg2OTFiZTAzZCIsCiAgICAgICJtZXRhZGF0YSIgOiB7CiAgICAgICAgIm1vZGVsIiA6ICJzbGltIgogICAgICB9CiAgICB9CiAgfQp9", Signature: "H9KtFHyAoGUBb0P8s9w+M/o67iD+/9cd1gLlvclCRTAwfGzfN3qIjpNaY/kqDJvCLURoo+BN+kUeKW43qpSRJ9GLOEeCX42HUXajicbCkQiXQeNhftuTXofHkyUZ6DorKpiCksAMI31j61DJ+aAwzINdFqkY3bCAjYUVQHxZe/xHZrsL0suu/IqIe83inIkcLOgrUJe3kTUgicaUxTcalJgqpNSrnwiNRx1VloKClALj6aHXiGMaU0vKzDg2ASeL7Rq+TWWDFB1MJT3oYCIJ3grW0gOVWlVtDUnUOWsGVpvfx3IsiQBH+8MeCE3vLMJsDNJ0yK3n94Yzo2CinqDrG4W150SDy4atnA3vlqGCDzvdzLYxoGASQ5OWTFgbREueNiBkxjm/8JQuI/ro3AnICKyvfxlQKbPuInne8xrNwZ2BBtlCZ7i9RZdQ0chtlIQD45/PYggeCr3rrjEDotMXIehFKBtI1tw3BRr+iebYTksT2UVpcgRhFT8vbCl/f9Bs0XiayO0lqlpIlB3771SiD71HfYhtcZzy+n1yFZfwRqF/EruPKQsjZdqfMVmoVjIxg5ZvfB/u7EMlNFC93Z/SojYpmvYLZaZ66bpjlsZG5rVv9Yf9wDKZvsXLK7ZT9MaFRJAUxZJGH6S3JgPvNiT/7RqmfnDs2iB5+ZnM16n1SbE="}]}, Id: [I; -1017219151, -1990116068, -1492045530, -1395399465]}}`

### `/qs paste` URL

ConsoleSpamFix Enabled

### Additional Context

![image](https://user-images.githubusercontent.com/51332006/152878144-7a20a140-f7c2-4da5-8d68-9c5c38357369.png)

**Comment by Ghost-chu** [comment]
please disable ConsoleSpamFix before report errors.

**Comment by SrBedrock** [comment]
> please disable ConsoleSpamFix before report errors.

I will update the issue after disabling the plugin.

**Comment by sandtechnology** [comment]
Please Try  https://ci.codemc.io/job/PotatoCraft-Studio/job/QuickShop-Reremake-SNAPSHOT/2213/

**Comment by SrBedrock** [comment]
Problem solved!
